# Generated by Django 3.2.3 on 2024-08-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopingcart',
            options={'verbose_name': 'Таблица рецептов, добавленных в корзину', 'verbose_name_plural': 'Таблица рецептов, добавленных в корзину'},
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient_amount', to='recipes.recipe'),
        ),
    ]
