#!/bin/bash
echo "Create follow..."
python manage.py shell -c "\
from users.models import Follow, User; \
Follow.objects.bulk_create([ \
Follow(user=User.objects.get(id=1), following=User.objects.get(id=3)), \
Follow(user=User.objects.get(id=1), following=User.objects.get(id=10)), \
Follow(user=User.objects.get(id=1), following=User.objects.get(id=20)), \
Follow(user=User.objects.get(id=2), following=User.objects.get(id=3)), \
Follow(user=User.objects.get(id=2), following=User.objects.get(id=9)), \
Follow(user=User.objects.get(id=2), following=User.objects.get(id=10)), \
Follow(user=User.objects.get(id=2), following=User.objects.get(id=21)), \
Follow(user=User.objects.get(id=3), following=User.objects.get(id=4)), \
Follow(user=User.objects.get(id=3), following=User.objects.get(id=6)), \
Follow(user=User.objects.get(id=3), following=User.objects.get(id=10)), \
Follow(user=User.objects.get(id=3), following=User.objects.get(id=13)), \
Follow(user=User.objects.get(id=3), following=User.objects.get(id=15)), \
Follow(user=User.objects.get(id=3), following=User.objects.get(id=23)), \
Follow(user=User.objects.get(id=4), following=User.objects.get(id=2)), \
Follow(user=User.objects.get(id=4), following=User.objects.get(id=10)), \
Follow(user=User.objects.get(id=5), following=User.objects.get(id=4)), \
Follow(user=User.objects.get(id=5), following=User.objects.get(id=28)), \
Follow(user=User.objects.get(id=6), following=User.objects.get(id=8)), \
Follow(user=User.objects.get(id=6), following=User.objects.get(id=9)), \
Follow(user=User.objects.get(id=6), following=User.objects.get(id=11)), \
Follow(user=User.objects.get(id=6), following=User.objects.get(id=22)), \
Follow(user=User.objects.get(id=8), following=User.objects.get(id=7)), \
Follow(user=User.objects.get(id=8), following=User.objects.get(id=22)), \
Follow(user=User.objects.get(id=9), following=User.objects.get(id=1)), \
Follow(user=User.objects.get(id=9), following=User.objects.get(id=15)), \
Follow(user=User.objects.get(id=9), following=User.objects.get(id=20)), \
Follow(user=User.objects.get(id=9), following=User.objects.get(id=23)), \
Follow(user=User.objects.get(id=10), following=User.objects.get(id=21)), \
Follow(user=User.objects.get(id=11), following=User.objects.get(id=5)), \
Follow(user=User.objects.get(id=11), following=User.objects.get(id=8)), \
Follow(user=User.objects.get(id=11), following=User.objects.get(id=15)), \
Follow(user=User.objects.get(id=11), following=User.objects.get(id=20)), \
Follow(user=User.objects.get(id=11), following=User.objects.get(id=21)), \
Follow(user=User.objects.get(id=13), following=User.objects.get(id=8)), \
Follow(user=User.objects.get(id=13), following=User.objects.get(id=9)), \
Follow(user=User.objects.get(id=13), following=User.objects.get(id=10)), \
Follow(user=User.objects.get(id=13), following=User.objects.get(id=11)), \
Follow(user=User.objects.get(id=13), following=User.objects.get(id=17)), \
Follow(user=User.objects.get(id=13), following=User.objects.get(id=19)), \
Follow(user=User.objects.get(id=13), following=User.objects.get(id=29)), \
Follow(user=User.objects.get(id=14), following=User.objects.get(id=1)), \
Follow(user=User.objects.get(id=14), following=User.objects.get(id=7)), \
Follow(user=User.objects.get(id=15), following=User.objects.get(id=25)), \
Follow(user=User.objects.get(id=16), following=User.objects.get(id=1)), \
Follow(user=User.objects.get(id=17), following=User.objects.get(id=14)), \
Follow(user=User.objects.get(id=17), following=User.objects.get(id=16)), \
Follow(user=User.objects.get(id=17), following=User.objects.get(id=21)), \
Follow(user=User.objects.get(id=17), following=User.objects.get(id=22)), \
Follow(user=User.objects.get(id=17), following=User.objects.get(id=28)), \
Follow(user=User.objects.get(id=18), following=User.objects.get(id=24)), \
Follow(user=User.objects.get(id=19), following=User.objects.get(id=7)), \
Follow(user=User.objects.get(id=19), following=User.objects.get(id=23)), \
Follow(user=User.objects.get(id=20), following=User.objects.get(id=7)), \
Follow(user=User.objects.get(id=20), following=User.objects.get(id=13)), \
Follow(user=User.objects.get(id=20), following=User.objects.get(id=15)), \
Follow(user=User.objects.get(id=20), following=User.objects.get(id=22)), \
Follow(user=User.objects.get(id=21), following=User.objects.get(id=9)), \
Follow(user=User.objects.get(id=21), following=User.objects.get(id=16)), \
Follow(user=User.objects.get(id=21), following=User.objects.get(id=29)), \
Follow(user=User.objects.get(id=22), following=User.objects.get(id=7)), \
Follow(user=User.objects.get(id=22), following=User.objects.get(id=14)), \
Follow(user=User.objects.get(id=22), following=User.objects.get(id=26)), \
Follow(user=User.objects.get(id=23), following=User.objects.get(id=8)), \
Follow(user=User.objects.get(id=23), following=User.objects.get(id=9)), \
Follow(user=User.objects.get(id=23), following=User.objects.get(id=14)), \
Follow(user=User.objects.get(id=23), following=User.objects.get(id=20)), \
Follow(user=User.objects.get(id=23), following=User.objects.get(id=21)), \
Follow(user=User.objects.get(id=23), following=User.objects.get(id=30)), \
Follow(user=User.objects.get(id=24), following=User.objects.get(id=19)), \
Follow(user=User.objects.get(id=25), following=User.objects.get(id=6)), \
Follow(user=User.objects.get(id=25), following=User.objects.get(id=17)), \
Follow(user=User.objects.get(id=26), following=User.objects.get(id=1)), \
Follow(user=User.objects.get(id=26), following=User.objects.get(id=9)), \
Follow(user=User.objects.get(id=26), following=User.objects.get(id=28)), \
Follow(user=User.objects.get(id=27), following=User.objects.get(id=4)), \
Follow(user=User.objects.get(id=28), following=User.objects.get(id=3)), \
Follow(user=User.objects.get(id=28), following=User.objects.get(id=4)), \
Follow(user=User.objects.get(id=29), following=User.objects.get(id=8)), \
Follow(user=User.objects.get(id=29), following=User.objects.get(id=17)), \
Follow(user=User.objects.get(id=30), following=User.objects.get(id=6)), \
Follow(user=User.objects.get(id=30), following=User.objects.get(id=10)), \
Follow(user=User.objects.get(id=30), following=User.objects.get(id=12)), \
]) \
count = Follow.objects.all().count()
print(f'Total entries made: {count}.')
"
echo "...follow created."